#!/bin/sh

eval $IMPORT_CEED

if [ "$#" -lt 1 ]; then
    printf "${RED}No file name${RESET}"
    exit
fi

enew

if [ -e "$@" ]; then
    finsert "$@"
    lcur_u ""
    rcur_u "$lf"
    rcur_u "$lf"
fi

setv path "$@"
setv dirty no

stat
