#!/bin/sh

eval $IMPORT_CEED

path=$(getv path)
if [ -n "$path" ]; then
    printf '"%s"' "$path"
else
    printf "unnamed buffer"
fi

if check dirty; then
    printf " (unsaved)"
fi

printf ", "

lslhfmt() {
    if [ "$1" -lt 1024 ]; then
        printf "${1}B"
    else
        echo "$1" | numfmt --to=iec
    fi
}

lslhfmt $(getv bytes)
