#!/bin/sh

. "$(command -v ceed.sh)"

path=$(getv path)
if [ -n "$path" ]; then
    printf '"%s"' "$path"
else
    printf "unnamed buffer"
fi

if check dirty; then
    printf " (unsaved)"
fi

printf ", "

getv bytes | numfmt --to=iec
